### ISSUE TITLE
Add release tag for 1.0.1

### ISSUE THREAD

**Issue by ath0mas** [rowanwins/turf-builder#12]
As the merge for Turf 3.5, I changed this package version to 1.0.2

We should create git tag "1.0.1" on last commit before this merge (e976dc4363d63c7aedbebaafd48748a43537f07e) ?

**Comment by rowanwins** [comment]
Hi @ath0mas ,

If this were a repo for people to actually download and use within their projects, or if it had more public appeal I'd say go for it but at the moment it's not really a repo for public use so I'm happy to ignore releases.

Thanks though :)

**Comment by ath0mas** [comment]
My use case was that I needed to rebuild for turf v3.0.x, and I had to find and checkout specific commit
Here is why I think a tag 1.0.1 "turf-3.0" would be nice ;)

**Comment by rowanwins** [comment]
ah I see @ath0mas , I'll try to see what I can do and attempt to remember to keep it up to date going forward.
