### ISSUE TITLE
Can not find @turf/truncate package

### ISSUE THREAD

**Issue by mickeyjohn** [rowanwins/turf-builder#15]
Hi,
From the https://turfjs-builder.herokuapp.com tool , I can not find turf/truncate package. Is it under another package and what is its name?

Thanks  a lot.

**Comment by rowanwins** [comment]
Gday @mickeyjohn

I have not updated turf builder in quite a while sorry so it is a fair way behind. I'll try to get round to running an update on it this evening. Cheers

**Comment by aliicex** [comment]
I've just opened pull request  #17  to update to Turf 5.1.6. This version of Turf includes the truncate package

**Comment by mickeyjohn** [comment]
Thanks for your help. It is listing the truncate package now.
