### ISSUE TITLE
Turf builder Heroku error

### ISSUE THREAD

**Issue by tcql** [rowanwins/turf-builder#5]
Copied from http://github.com/Turfjs/turf/issues/378

---

When I try to build a custom file with the following options, it is giving a application error in download. 
Selected options: 
![screen shot 2016-05-18 at 17 09 34](https://cloud.githubusercontent.com/assets/1588744/15366260/64b0e738-1d1b-11e6-9018-f4bfafceb145.png)

Error: 
![screen shot 2016-05-18 at 17 10 05](https://cloud.githubusercontent.com/assets/1588744/15366263/67fddbe4-1d1b-11e6-8d75-34d16c365c85.png)

**Comment by rowanwins** [comment]
I've updated the app to run using turf v3 and all seems to be well

**Comment by kristfal** [comment]
@rowanwins this seems to be broken again.

Selection (just for reference, I think any selection crashes atm):

<img width="867" alt="skjermbilde 2016-05-21 00 30 59" src="https://cloud.githubusercontent.com/assets/5638107/15443799/6791e610-1eeb-11e6-9502-5976fb18b53b.png">

App crashes as described in initial post.

**Comment by rowanwins** [comment]
Gday @kristfal , yeah unfortunantly Im experiencing some issues with heroku , still trying to work out what's going on :(

Thanks for reporting
