### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by krem06** [rowanwins/turf-builder#6]
Thanks for the correction you made but I am still getting the message 'Application Error'...and now with any sub module selected.

It would be great if you could have a further look, thank you very much for this nice tool !

**Comment by rowanwins** [comment]
Thanks for the report @krem06 , yeah I've seen the error, for some reason heroku is being a bit finickity :(

Anyway I'm working on it

**Comment by hrishiballal** [comment]
![screen shot 2016-06-08 at 08 55 22](https://cloud.githubusercontent.com/assets/1588744/15886823/eaf4a5be-2d56-11e6-8894-a1c7eee3bca0.png)
When I use the selections attached, while I am not getting a Application error message, nothing happens.

**Comment by rowanwins** [comment]
Gday @hrishiballal & @krem06 

Have just pushed up a new version which seems to be playing nicely with Heroku. Let me know if you experience any further issues.

**Comment by krem06** [comment]
Thank you for the followup ! But when I try, the js console gives me the following error:
jquery.min.js:4 POST https://turfjs-builder.herokuapp.com/build 503 (Service Unavailable)

After some further tests I could generate 1 version with only 'buffer', but when I try again, I get the same error as above... Could it be that we go above the allocated resources from heroku ? Several people trying at the same time is bad ?

Let me know if I can make some further tests ;)

**Comment by rowanwins** [comment]
Hmmm that's a shame @krem06 In my testing 

I haven't been able to crash it yet, I've selected up to 10 modules which come out at over 1MB and it still runs fine.

Perhaps try and do a hard reload on the page (having dev tools open does this). Which does raise a question, what browser are you using?
