### ISSUE TITLE
No download prompt in Firefox

### ISSUE THREAD

**Issue by ath0mas** [rowanwins/turf-builder#7]
Build and download work fine in Chrome
In Firefox (47+) I think build is ok, but download prompt never pops

Error in console: `Syntax error __________ build:1:1`

**Comment by rowanwins** [comment]
Thanks for the report @ath0mas I'll take a look into it.

**Comment by rowanwins** [comment]
HI @ath0mas I believe I've now resolved this.

**Comment by ath0mas** [comment]
Download starts in Firefox now :+1: 

but download prompt tells "with file type: SQL File", and file saved is `turf_dddMDDYYYY.min.js.sql`

**Comment by rowanwins** [comment]
resolved, thanks for the attention to detail!

**Comment by ath0mas** [comment]
Perfect, thanks :wink: @rowanwins
